### PR TITLE
Fix USB enumeration

### LINKED ISSUE #27: USB discovery error
Hi,
I'm running the device-plugin and I'm trying to discover `/dev/fuse`, but the device is not found and in the kubelet log I see these errors:
```
May 10 11:46:45 xxxx kubelet[14485]: I0510 11:46:45.807900   14485 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"device-plugin\" (UniqueName: \"kubernetes.io/host-path/64159588-4463-452f-941e-7f11d39411f4-device-plugin\") pod \"generic-device-plugin-hfxdl\" (UID: \"64159588-4463-452f-941e-7f11d39411f4\") " pod="default/generic-device-plugin-hfxdl"
May 10 11:46:45 xxxx kubelet[14485]: I0510 11:46:45.808061   14485 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-5lhdq\" (UniqueName: \"kubernetes.io/projected/64159588-4463-452f-941e-7f11d39411f4-kube-api-access-5lhdq\") pod \"generic-device-plugin-hfxdl\" (UID: \"64159588-4463-452f-941e-7f11d39411f4\") " pod="default/generic-device-plugin-hfxdl"
May 10 11:46:45 xxxx kubelet[14485]: I0510 11:46:45.808211   14485 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"dev\" (UniqueName: \"kubernetes.io/host-path/64159588-4463-452f-941e-7f11d39411f4-dev\") pod \"generic-device-plugin-hfxdl\" (UID: \"64159588-4463-452f-941e-7f11d39411f4\") " pod="default/generic-device-plugin-hfxdl"
May 10 11:46:49 xxxx kubelet[14485]: I0510 11:46:49.019886   14485 manager.go:422] "Got registration request from device plugin with resource" resourceName="squat.ai/fuse"
May 10 11:46:49 xxxx kubelet[14485]: E0510 11:46:49.118835   14485 endpoint.go:107] "listAndWatch ended unexpectedly for device plugin" err="rpc error: code = Unknown desc = failed to refresh devices: failed to discover usb devices: open /sys/bus/usb/devices/: no such file or directory" resourceName="squat.ai/fuse"
```

On the worker node the directory `/sys/bus/usb/devices/` doesn't exist:

```
xxxx@xxxx:/$ ls -la /sys/bus/
total 0
drwxr-xr-x 30 root root 0 May 10 09:55 .
dr-xr-xr-x 13 root root 0 May 10 09:55 ..
drwxr-xr-x  4 root root 0 May 10 09:55 acpi
drwxr-xr-x  4 root root 0 May 10 09:55 cec
drwxr-xr-x  4 root root 0 May 10 09:55 clockevents
drwxr-xr-x  4 root root 0 May 10 09:55 clocksource
drwxr-xr-x  4 root root 0 May 10 09:55 container
drwxr-xr-x  4 root root 0 May 10 09:55 cpu
drwxr-xr-x  4 root root 0 May 10 09:55 dax
drwxr-xr-x  4 root root 0 May 10 09:55 edac
drwxr-xr-x  4 root root 0 May 10 09:55 event_source
drwxr-xr-x  4 root root 0 May 10 09:55 gpio
drwxr-xr-x  4 root root 0 May 10 09:55 i2c
drwxr-xr-x  4 root root 0 May 10 09:55 machinecheck
drwxr-xr-x  4 root root 0 May 10 09:55 memory
drwxr-xr-x  4 root root 0 May 10 09:55 mipi-dsi
drwxr-xr-x  4 root root 0 May 10 09:55 node
drwxr-xr-x  4 root root 0 May 10 09:55 nvmem
drwxr-xr-x  5 root root 0 May 10 09:55 pci
drwxr-xr-x  4 root root 0 May 10 09:55 pci_express
drwxr-xr-x  4 root root 0 May 10 09:55 platform
drwxr-xr-x  4 root root 0 May 10 09:55 pnp
drwxr-xr-x  4 root root 0 May 10 09:55 rbd
drwxr-xr-x  4 root root 0 May 10 09:55 scsi
drwxr-xr-x  4 root root 0 May 10 09:55 serial
drwxr-xr-x  4 root root 0 May 10 09:55 serio
drwxr-xr-x  4 root root 0 May 10 09:55 spi
drwxr-xr-x  4 root root 0 May 10 09:55 workqueue
drwxr-xr-x  4 root root 0 May 10 09:55 xen
drwxr-xr-x  4 root root 0 May 10 09:55 xen-backend
```

This is the yaml file that I applied:
``` yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: generic-device-plugin
  namespace: default
  labels:
    app.kubernetes.io/name: generic-device-plugin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: generic-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: generic-device-plugin
    spec:
      priorityClassName: system-node-critical
      containers:
      - image: squat/generic-device-plugin
        args:
        - --device
        - |
          name: fuse
          groups:
            - count: 10
              paths:
                - path: /dev/fuse
        name: generic-device-plugin
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 10Mi
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
  updateStrategy:
    type: RollingUpdate
```

On the source code I found this:

https://github.com/squat/generic-device-plugin/blob/013b39297e99d0bccb6cbb9e60c828e710a16e40/deviceplugin/usb.go#L134

How about checking if the folder exists instead of just throwing the error if it doesn't?

### PR DESCRIPTION
**Pull request by vigmat28**
Resolve #27

### CODE REVIEW

File: deviceplugin/usb.go [hunk 1]
```diff
@@ -241,43 +241,49 @@ func searchUSBDevices(devices *[]usbDevice, vendor USBID, product USBID) (devs [
...
 	for _, group := range gp.ds.Groups {
 		var paths []string
-		usbDevs, err := enumerateUSBDevices(usbDevicesDir)
-		if err != nil {
-			return devices, err
-		}
-		for _, dev := range group.USBSpecs {
-			matches, err := searchUSBDevices(&usbDevs, dev.Vendor, dev.Product)
+
+		if !gp.skipUSBEnumeration {
```
Comment (squat) [inline deviceplugin/usb.go:245]: let's invert this so that we avoid all of the extra nesting:
```suggestion
		if gp.skipUSBEnumeration {
			return
		}
```

**Review by squat — COMMENTED** [review]
Thanks a lot for this contribution @vigmat28 :))))
I left a couple of comments and questions. Please take a look when you can

File: deviceplugin/usb.go (hunk 1 above)
Comment (squat) [reply deviceplugin/usb.go:245]: Ahh i love that second idea. Let's go with that: only enable USB device discovery if a USB device spec is defined

**Review by squat — APPROVED** [review]
LGTM! Thanks :)))

File: deviceplugin/usb.go [hunk 2]
```diff
@@ -243,7 +243,8 @@ func (gp *GenericPlugin) discoverUSB() (devices []device, err error) {
 		var paths []string
 		usbDevs, err := enumerateUSBDevices(usbDevicesDir)
 		if err != nil {
-			return devices, err
+			level.Warn(gp.logger).Log("msg", fmt.Sprintf("failed to enumerate usb devices: %s", err.Error()))
```
Comment (squat) [inline deviceplugin/usb.go:246]:
```suggestion
			level.Warn(gp.logger).Log("msg", fmt.Sprintf("failed to enumerate usb devices: %v", err))
```

**Comment by squat** [comment]
Another thing to note is that this engagement will also reduce memory usage of the device plugin whenever USB discovery is disabled.

xref: #17
